FROM python:3.9-slim
ENV DEBIAN_FRONTEND=noninteractive 

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    bash \
    git \
    libzmq3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN python3 -m pip install --upgrade pip && \
    pip3 --no-cache-dir install -r requirements.txt && \
    pip3 install git+https://github.com/kshalm/zmqhelpers.git